/* Heroes (map data) and the public Tier List (no supporter content; Boss / AoE / AFK / Utility / Tank) */
(function (K) {
  const { W, esc, link, tag, fmt, gen, P, INDEX, KL, subtabs } = K;
  const HM = W.heroes, PORT = W.portraits || {};
  const LINEAGES = [...new Set(HM.filter(h => !h.skin).map(h => h.lineage))].sort();
  const TLB = {}; for (const x of ((W.tierlist || {}).heroes || [])) TLB[x.name] = x;
  const LSORT = [...LINEAGES].sort((a, b) => ((TLB[b] || {}).boss || 0) - ((TLB[a] || {}).boss || 0));
  const roleOf = r => r ? (r.role || '') : '';
  const img = (src, sz) => src ? `<img src="${src}" alt="" loading="lazy" style="width:${sz}px;height:${sz}px;object-fit:cover;border-radius:6px">` : '';
  const abilTable = h => `<div class="tbl"><table><tr><th>Key</th><th>Ability</th><th>Type</th><th>Description</th></tr>${(h.abilities || []).filter(a => !/^(Move to|Inventory|Attack$|Stop$|Hold|Patrol)/.test(a.name)).map(a => `<tr><td><b>${esc(a.hotkey || a.learn_hotkey || '')}</b></td><td>${esc(a.name)}${a.levels > 1 ? ` <span class="small">(${a.levels} levels)</span>` : ''}</td><td class="small">${a.kind === 'transform' ? 'passive · transforms' : a.kind === 'press' ? (/^Susanoo|Elderwood|Colossus/.test(a.name) ? 'press · transforms' : 'press') : a.kind === 'passive' ? 'passive' : (a.passive ? 'passive' : 'press')}</td><td class="small pre">${esc(a.tooltip || '')}</td></tr>`).join('')}</table></div>`;
  const heroCard = (h, pic) => `<div class="card">${pic ? `<img src="${pic}" alt="" loading="lazy" style="max-width:200px;max-height:200px;border-radius:6px;float:right;margin:0 0 8px 12px">` : ''}<h3>Tier ${h.tier} · ${esc(h.name)}${h.donation_flag ? tag('supporter hero', 'acc') : ''}${h.skin ? tag('skin variant') : ''}</h3><p class="small">${esc(h.obtain || '')}</p><div class="kv"><b>Primary</b><span>${esc(h.stat)}</span><b>Base</b><span>HP ${fmt(h.hp)} · STR ${esc(h.str)} · AGI ${esc(h.agi)} · INT ${esc(h.int)}</span><b>Growth / level</b><span>STR +${esc(h.str_plus)} · AGI +${esc(h.agi_plus)} · INT +${esc(h.int_plus)}</span></div>${abilTable(h)}</div>`;
  const FORMS = W.forms || {};
  const formsHtml = (l, tier) => { const fl = ((FORMS[l] || {}).tiers || {})[String(tier)] || []; return fl.map(f => `<div class="card"><h4 style="margin-top:0">Transformation · ${esc(f.form_name)}</h4><p class="small">${esc(f.trigger || '')}${f.duration_s ? ` · ${f.duration_s} s` : ''}${f.cooldown_s ? ` · every ${f.cooldown_s} s` : ''}${f.uptime != null ? ` · about ${Math.round(f.uptime * 100)}% of the time` : ''}</p>${(f.adds || []).length ? `<p><b>Adds:</b> ${f.adds.map(esc).join(' · ')}</p>` : ''}${(f.loses || []).length ? `<p><b>Loses:</b> ${f.loses.map(esc).join(' · ')}</p>` : ''}${(f.abilities || []).length ? `<div class="tbl"><table><tr><th>Ability</th><th>Type</th><th>Description</th></tr>${f.abilities.map(a => `<tr><td>${esc(a.name)}</td><td class="small">${esc(a.kind || '')}</td><td class="small pre">${esc(a.tooltip || '')}</td></tr>`).join('')}</table></div>` : ''}</div>`).join(''); };
  const formTag = l => (FORMS[l] && FORMS[l].tag) ? ` <span class="tag magic">${esc(FORMS[l].tag)}</span>` : '';
  const TLBY = {}; for (const t of ((W.tierlist || {}).heroes || [])) TLBY[t.name] = t;
  const hasTL = Object.keys(TLBY).length > 0;
  P.heroes = () => `<h2>Heroes</h2><p class="small">${LINEAGES.length} heroes, ${LINEAGES.filter(l => !HM.find(h => h.lineage === l && h.donation_flag)).length} free. Tier 2 comes with the class change. Grades: ${link('tierlist', '', 'tier list')}.</p>
  <div class="tbl"><table class="sortable"><tr><th></th><th>Hero</th><th>Stat</th><th>Access</th>${hasTL ? '<th>Role</th>' : ''}</tr>${[...LINEAGES].map(l => { const t = HM.find(h => h.lineage === l && h.tier === 1 && !h.skin); const tl = TLBY[l]; return `<tr><td>${img((PORT[l] || [])[1] || (PORT[l] || [])[0], 48)}</td><td>${link('hero', l, l)}</td><td>${t ? esc(t.stat) : ''}</td><td class="small">${t && t.donation_flag ? 'supporter' : 'free'}</td>${hasTL ? `<td class="small">${tl ? esc(roleOf(tl)) : ''}</td>` : ''}</tr>`; }).join('')}</table></div>${hasTL ? '<p class="small">Role tags say what a kit can do, not what the hero is: Healer means it has a way to heal the party, not that it only heals, no Damage tag does not mean it deals no damage.</p>' : ''}`;
  P.hero = l => {
    const hs = HM.filter(h => h.lineage === l && !h.skin && h.tier <= 2).sort((a, b) => a.tier - b.tier); if (!hs.length) return '<p>Unknown hero.</p>';
    const tl = TLBY[l]; const pics = PORT[l] || []; const h1 = hs.find(h => h.tier === 1), h2 = hs.find(h => h.tier === 2); const main = h2 || h1;
    const S = tl ? safety(tl) : ['', ''];
    return `<h2>${esc(l)} ${hs.some(h => h.donation_flag) ? tag('supporter hero', 'acc') : tag('free', 'ok')}</h2>
    <div class="card">${pics[1] || pics[0] ? `<img src="${pics[1] || pics[0]}" alt="" loading="lazy" style="max-width:160px;max-height:160px;border-radius:6px;float:right;margin:0 0 8px 12px">` : ''}
    <div class="kv"><b>Main stat</b><span>${main ? esc(main.stat) : ''}</span>${tl ? `<b>Role</b><span>${esc(roleOf(tl))}${tl.role_why ? ` <span class="small">- ${esc(tl.role_why)}</span>` : ''} <span class="small">(tags say what the kit can do, not what the hero is)</span></span><b>Tier list</b><span>boss ${fmt(tl.boss)} · AoE ${fmt(tl.aoe)} · AFK ${fmt(tl.afk)} · utility ${fmt(tl.utility)} · tank ${fmt(tl.tank)} · ${link('tierlist', '', 'compare')}</span><b>If left alone</b><span><span class="tag ${S[1]}">${S[0]}</span> <span class="small">${esc(tl.afk_notes || '')}</span></span>` : ''}${tl && tl.notes ? `<b>In short</b><span>${esc(tl.notes)}</span>` : ''}${tl && (tl.unique_effects || []).length ? `<b>Only this hero</b><span>${tl.unique_effects.map(esc).join(' · ')}</span>` : ''}</div><div style="clear:both"></div></div>
    ${h1 ? `<h3>Tier 1</h3>${abilTable(h1)}${formsHtml(l, 1)}` : ''}
    ${h2 ? `<h3>Tier 2</h3>${abilTable(h2)}${formsHtml(l, 2)}` : ''}
    ${tl ? `<details><summary>How its tier-list scores are built</summary>${tl.attack_speed ? `<p class="small"><b>Attack speed:</b> ${esc(tl.attack_speed.text || '')}</p>` : ''}${(tl.components || []).length ? `<h4>Damage</h4><div class="tbl"><table><tr><th>Effect</th><th>Value</th></tr>${tl.components.map(c => `<tr><td>${esc(c.n)}</td><td class="small">${esc(c.value_text || '')}</td></tr>`).join('')}</table></div>` : ''}${(tl.utility_parts || []).length ? `<h4>Utility</h4><div class="tbl"><table><tr><th>Ability</th><th>Why</th><th class="num">Points</th></tr>${tl.utility_parts.map(c => `<tr><td>${esc(c.ability)}</td><td class="small">${esc(c.why)}</td><td class="num">${esc(c.value)}</td></tr>`).join('')}</table></div>` : ''}${tl.sustain != null ? `<h4>Survival</h4><p class="small">Can out-heal ${fmt(tl.sustain_phys)}% of max HP per second of physical damage and ${fmt(tl.sustain_spell)}% of spell damage${tl.afk_sustain != null ? `; ${fmt(tl.afk_sustain)}% per second without clicking` : ''}. Effective HP against one hit: ${fmt(tl.burst_ehp)}.</p>` : ''}${(tl.tank_parts || []).length ? `<div class="tbl"><table><tr><th>Part</th><th>Ability</th><th>What counts</th></tr>${tl.tank_parts.map(c => `<tr><td class="small">${esc(c.part || '')}</td><td>${esc(c.ability)}</td><td class="small">${esc(c.why)}</td></tr>`).join('')}</table></div>` : ''}</details>` : ''}`;
  };
  const role = r => r.role || '';
  const safety = o => { if (o.afk_safe == null) { const r = o.afk_passive && o.afk_passive.recovery_pct_per_s; if (r == null) return ['', '']; return r > 0.1 ? ['Survives', 'ok'] : ['Dies if left alone', 'bad']; } return o.afk_safe ? ['Survives', 'ok'] : ['Dies if left alone', 'bad']; };
  const GRADE = v => v >= .8 ? 'S' : v >= .55 ? 'A' : v >= .35 ? 'B' : v >= .2 ? 'C' : 'D';
  const gtag = (g, raw) => `<span class="grade g${g}" title="${esc(raw)}">${g}</span>`;
  P.tierlist = (_, f) => {
    const T = W.tierlist; if (!T || !T.heroes) return '<h2>Tier list</h2><p class="small">Not built yet.</p>';
    const COLS = ['solo', 'boss', 'aoe', 'afk', 'utility', 'tank']; const key = COLS.includes(f.sort) ? f.sort : 'solo'; const f2p = f.f2p === '1', early = f.early === '1';
    const kain = f.kain === '1';
    const withKain = o => { const b = o.tank_breakdown; if (!b || !kain) return o; const R = (b.recovery_pct_per_s || 0) + 2 * (o.swings_afk || o.swings || 0); const s = ((R / Math.max(0.05, (b.phys_damage_taken || 1) * (1 - (b.evasion || 0)))) + R / Math.max(0.05, b.spell_damage_taken || 1)) / 2; const ss = 100 * Math.log(1 + s) / Math.log(1 + (b.best_sustain || s)); return { ...o, tank: Math.max(0, Math.min(100, Math.round((0.5 * ss + 0.5 * (b.burst_score || 0)) * (b.nonstr_factor || 1)))), afk_sustain: +(o.afk_sustain + 2 * (o.swings_afk || 0)).toFixed(2), afk_passive: { ...o.afk_passive, recovery_pct_per_s: R } }; };
    const src = r => withKain(early && r.t1 ? r.t1 : r);
    const pool = T.heroes.filter(r => !f2p || r.free !== false);
    const max = {}; for (const k of ['boss', 'aoe', 'afk', 'utility', 'tank']) max[k] = Math.max(1, ...pool.map(r => src(r)[k] || 0));
    const norm = (r, k) => (src(r)[k] || 0) / max[k];
    const solo = r => 0.35 * norm(r, 'boss') + 0.1 * norm(r, 'aoe') + 0.55 * norm(r, 'tank');
    const SAFE = { 'Survives': 1, 'Dies if left alone': 0.4 };
    const afkv = r => norm(r, 'afk');
    const afkMax = Math.max(0.001, ...pool.map(afkv));
    const val = (r, k) => k === 'solo' ? solo(r) : k === 'afk' ? afkv(r) / afkMax : norm(r, k);
    const rows = [...pool].sort((a, b) => val(b, key) - val(a, key)); const topSolo = Math.max(...pool.map(solo), 0.001);
    const LBL = { solo: 'Solo', boss: 'Boss damage', aoe: 'AoE damage', afk: 'AFK farm', utility: 'Utility (party)', tank: 'Tank (survival)' };
    const colv = k => pool.map(x => val(x, k)); const rankG = (k, v) => { if (!(v > 0)) return 'D'; const vs = colv(k); const above = vs.filter(x => x > v).length / vs.length; const mx = Math.max(...vs, 0.001); const g = above < 0.2 ? 'S' : above < 0.45 ? 'A' : above < 0.72 ? 'B' : above < 0.9 ? 'C' : 'D'; const cap = v < 0.15 * mx ? 'C' : v < 0.35 * mx ? 'B' : 'S'; return 'SABCD'.indexOf(g) > 'SABCD'.indexOf(cap) ? g : cap; };
    const cellG = (r, k) => k === 'solo' ? gtag(rankG('solo', solo(r)), 'solo score ' + Math.round(100 * solo(r) / topSolo)) : k === 'afk' ? gtag(rankG('afk', val(r, 'afk')), 'AFK farm ' + fmt(src(r).afk) + ' · no-click damage × stat per second: ' + fmt(src(r).afk_dps) + ' · no-click survival ' + fmt(src(r).afk_tank) + ' · ' + safety(src(r))[0]) : gtag(rankG(k, val(r, k)), (k === 'utility' || k === 'tank' ? '' : '× stat per second: ') + fmt(src(r)[k]));
    return `<h2>Hero tier list</h2><p class="small">Tier 2 of each hero, no supporter items, all stats bought. Grades are by rank within each column (S = top fifth, A = next quarter, B = middle, C, D), hover a grade for the number.</p><div class="card warn"><p style="margin:0 0 8px;font-size:17px"><b>READ THIS FIRST. This list is one person's math and opinion. It is not the truth.</b></p><ul style="margin:0"><li>Grades come from ability numbers, not from playing. Anything within one grade is a coin flip.</li><li>It ignores <b>range</b> (ranged vs melee), <b>boss mechanics</b> (a revive, a taunt or magic immunity can beat any damage number on a given boss), <b>misses</b> (evasion, spell immunity) and <b>your attack speed</b> (one mid-game glove is assumed, at the cap mana-loop heroes like Abyss are far stronger).</li><li>Every hero has a place in a party. An aura nobody else has can matter more than any grade here.</li><li><b>Role tags</b> say what a kit can do, not what the hero is: Healer = it has a way to heal the party, not that it only heals, no Damage tag does not mean it deals no damage.</li><li><b>Try heroes yourself.</b> Do not use this list to call for buffs or nerfs.</li></ul></div><details><summary>How the scores are built</summary><ul>${(T.assumptions || []).map(x => `<li>${esc(x)}</li>`).join('')}</ul></details>
    ${subtabs('tierlist', 'sort', Object.entries(LBL), key)}<p><label><input type="checkbox" id="f2p" ${f2p ? 'checked' : ''}> Free to play only</label> &nbsp; <label><input type="checkbox" id="early" ${early ? 'checked' : ''}> Tier 1</label> &nbsp; <label><input type="checkbox" id="kain" ${kain ? 'checked' : ''}> With Kain (lifesteal pet, 2% max HP per attack)</label></p>
    <div class="tbl"><table class="sortable"><tr><th>#</th><th>Hero</th><th>Solo</th><th>Boss</th><th>AoE</th><th>AFK farm</th><th>Utility</th><th>Tank</th><th>If left alone</th><th>Note</th></tr>${rows.map((r, i) => { const s = safety(src(r)); return `<tr><td>${i + 1}</td><td style="white-space:nowrap">${img((PORT[r.name] || [])[1] || (PORT[r.name] || [])[0], 36)} ${link('hero', r.name, r.name)} ${r.free === false ? tag('supporter', 'acc') : ''}<br><span class="small">${esc(role(src(r)))}</span></td><td>${cellG(r, 'solo')}</td><td>${cellG(r, 'boss')}</td><td>${cellG(r, 'aoe')}</td><td>${cellG(r, 'afk')}</td><td>${cellG(r, 'utility')}</td><td>${cellG(r, 'tank')}</td><td>${s[0] ? `<span class="tag ${s[1]}" title="${src(r).afk_sustain != null ? 'out-heals ' + fmt(src(r).afk_sustain) + '% of max HP per second without clicking' : ''}">${s[0]}</span>` : ''}</td><td class="small">${esc(r.notes || '')}${(src(r).unique_effects || []).length ? `<br>${src(r).unique_effects.map(u => `<span class="tag ok" style="text-transform:none;letter-spacing:0">only hero: ${esc(u)}</span>`).join(' ')}` : ''}</td></tr>`; }).join('')}</table></div>
`;
  };
  K.hooks.push((page, out) => { if (page !== 'tierlist') return; for (const id of ['f2p', 'early', 'kain']) { const cb = out.querySelector('#' + id); if (cb) cb.addEventListener('change', () => { K.filters[id] = cb.checked ? '1' : '0'; K.route(); }); } });
  KL.hero = 'Hero / ability';
  for (const h of HM) { if (h.skin || h.tier > 2) continue; INDEX.push({ k: 'hero', id: h.lineage, t: h.lineage + ' tier ' + h.tier, s: 'hero · ' + h.stat + (h.donation_flag ? ' · supporter' : ''), w: 3 }); for (const a of (h.abilities || [])) if (!/^(Move to|Inventory)/.test(a.name)) INDEX.push({ k: 'hero', id: h.lineage, t: a.name + ' (' + h.name + ')', s: 'ability · ' + String(a.tooltip || '').slice(0, 100), w: 1 }); }
})(window.WK);
