/* Heroes (map data) and the public Tier List (no supporter content; Boss / AoE / AFK / Utility / Tank) */
(function (K) {
  const { W, esc, link, tag, fmt, gen, P, INDEX, KL, subtabs } = K;
  const HM = W.heroes, PORT = W.portraits || {};
  const LINEAGES = [...new Set(HM.filter(h => !h.skin).map(h => h.lineage))].sort();
  const TLB = {}; for (const x of ((W.tierlist || {}).heroes || [])) TLB[x.name] = x;
  const LSORT = [...LINEAGES].sort((a, b) => ((TLB[b] || {}).boss || 0) - ((TLB[a] || {}).boss || 0));
  const roleOf = r => r ? (r.role || '') : '';
  const img = (src, sz) => src ? `<img src="${src}" alt="" style="width:${sz}px;height:${sz}px;object-fit:cover;border-radius:6px">` : '';
  const abilTable = h => `<div class="tbl"><table><tr><th>Key</th><th>Ability</th><th>Type</th><th>Description</th></tr>${(h.abilities || []).filter(a => !/^(Move to|Inventory|Attack$|Stop$|Hold|Patrol)/.test(a.name)).map(a => `<tr><td><b>${esc(a.hotkey || a.learn_hotkey || '')}</b></td><td>${esc(a.name)}${a.levels > 1 ? ` <span class="small">(${a.levels} levels)</span>` : ''}</td><td class="small">${a.kind === 'transform' ? 'passive · transforms' : a.kind === 'press' ? (/^Susanoo|Elderwood|Colossus/.test(a.name) ? 'press · transforms' : 'press') : a.kind === 'passive' ? 'passive' : (a.passive ? 'passive' : 'press')}</td><td class="small pre">${esc(a.tooltip || '')}</td></tr>`).join('')}</table></div>`;
  const heroCard = (h, pic) => `<div class="card">${pic ? `<img src="${pic}" alt="" style="max-width:200px;max-height:200px;border-radius:6px;float:right;margin:0 0 8px 12px">` : ''}<h3>Tier ${h.tier} · ${esc(h.name)}${h.donation_flag ? tag('supporter hero', 'acc') : ''}${h.skin ? tag('skin variant') : ''}</h3><p class="small">${esc(h.obtain || '')}</p><div class="kv"><b>Primary</b><span>${esc(h.stat)}</span><b>Base</b><span>HP ${fmt(h.hp)} · STR ${esc(h.str)} · AGI ${esc(h.agi)} · INT ${esc(h.int)}</span><b>Growth / level</b><span>STR +${esc(h.str_plus)} · AGI +${esc(h.agi_plus)} · INT +${esc(h.int_plus)}</span></div>${abilTable(h)}</div>`;
  const FORMS = W.forms || {};
  const formsHtml = (l, tier) => { const fl = ((FORMS[l] || {}).tiers || {})[String(tier)] || []; return fl.map(f => `<div class="card"><h4 style="margin-top:0">Transformation · ${esc(f.form_name)}</h4><p class="small">${esc(f.trigger || '')}${f.duration_s ? ` · ${f.duration_s} s` : ''}${f.cooldown_s ? ` · every ${f.cooldown_s} s` : ''}${f.uptime != null ? ` · about ${Math.round(f.uptime * 100)}% of the time` : ''}</p>${(f.adds || []).length ? `<p><b>Adds:</b> ${f.adds.map(esc).join(' · ')}</p>` : ''}${(f.loses || []).length ? `<p><b>Loses:</b> ${f.loses.map(esc).join(' · ')}</p>` : ''}${(f.abilities || []).length ? `<div class="tbl"><table><tr><th>Ability</th><th>Type</th><th>Description</th></tr>${f.abilities.map(a => `<tr><td>${esc(a.name)}</td><td class="small">${esc(a.kind || '')}</td><td class="small pre">${esc(a.tooltip || '')}</td></tr>`).join('')}</table></div>` : ''}</div>`).join(''); };
  const formTag = l => (FORMS[l] && FORMS[l].tag) ? ` <span class="tag magic">${esc(FORMS[l].tag)}</span>` : '';
  const TLBY = {}; for (const t of ((W.tierlist || {}).heroes || [])) TLBY[t.name] = t;
  const hasTL = Object.keys(TLBY).length > 0;
  P.heroes = () => `<h2>Heroes</h2><p class="small">${LINEAGES.length} heroes, ${LINEAGES.filter(l => !HM.find(h => h.lineage === l && h.donation_flag)).length} free. Tier 2 comes with the class change. Grades: ${link('tierlist', '', 'tier list')}.</p>
  <div class="tbl"><table class="sortable"><tr><th></th><th>Hero</th><th>Stat</th><th>Access</th>${hasTL ? '<th>Role</th>' : ''}</tr>${[...LINEAGES].map(l => { const t = HM.find(h => h.lineage === l && h.tier === 1 && !h.skin); const tl = TLBY[l]; return `<tr><td>${img((PORT[l] || [])[1] || (PORT[l] || [])[0], 48)}</td><td>${link('hero', l, l)}</td><td>${t ? esc(t.stat) : ''}</td><td class="small">${t && t.donation_flag ? 'supporter' : 'free'}</td>${hasTL ? `<td class="small">${tl ? esc(roleOf(tl)) : ''}</td>` : ''}</tr>`; }).join('')}</table></div>${hasTL ? '<p class="small">Role tags say what a kit can do, not what the hero is: Healer means it heals the party at least 8% of max HP per second, no Damage tag does not mean it deals no damage.</p>' : ''}`;
  P.hero = l => {
    const hs = HM.filter(h => h.lineage === l && !h.skin && h.tier <= 2).sort((a, b) => a.tier - b.tier); if (!hs.length) return '<p>Unknown hero.</p>';
    const tl = TLBY[l]; const pics = PORT[l] || []; const h1 = hs.find(h => h.tier === 1), h2 = hs.find(h => h.tier === 2); const main = h2 || h1;
    const S = tl ? safety(tl) : ['', ''];
    return `<h2>${esc(l)} ${hs.some(h => h.donation_flag) ? tag('supporter hero', 'acc') : tag('free', 'ok')}</h2>
    <div class="card">${pics[1] || pics[0] ? `<img src="${pics[1] || pics[0]}" alt="" style="max-width:160px;max-height:160px;border-radius:6px;float:right;margin:0 0 8px 12px">` : ''}
    <div class="kv"><b>Main stat</b><span>${main ? esc(main.stat) : ''}</span>${tl ? `<b>Role</b><span>${esc(roleOf(tl))}${tl.role_why ? ` <span class="small">- ${esc(tl.role_why)}</span>` : ''} <span class="small">(tags say what the kit can do, not what the hero is)</span></span><b>Tier list</b><span>boss ${fmt(tl.boss)} · AoE ${fmt(tl.aoe)} · AFK ${fmt(tl.afk)} · utility ${fmt(tl.utility)} · tank ${fmt(tl.tank)} · ${link('tierlist', '', 'compare')}</span><b>If left alone</b><span><span class="tag ${S[1]}">${S[0]}</span> <span class="small">${esc(tl.afk_notes || '')}</span></span>` : ''}${tl && tl.notes ? `<b>In short</b><span>${esc(tl.notes)}</span>` : ''}${tl && (tl.unique_effects || []).length ? `<b>Only this hero</b><span>${tl.unique_effects.map(esc).join(' · ')}</span>` : ''}</div><div style="clear:both"></div></div>
    ${h1 ? `<h3>Tier 1</h3>${abilTable(h1)}${formsHtml(l, 1)}` : ''}
    ${h2 ? `<h3>Tier 2</h3>${abilTable(h2)}${formsHtml(l, 2)}` : ''}
    ${tl ? `<details><summary>How its tier-list scores are built</summary>${tl.attack_speed ? `<p class="small"><b>Attack speed:</b> ${esc(tl.attack_speed.text || '')}</p>` : ''}${(tl.components || []).length ? `<h4>Damage</h4><div class="tbl"><table><tr><th>Effect</th><th>Value</th></tr>${tl.components.map(c => `<tr><td>${esc(c.n)}</td><td class="small">${esc(c.value_text || '')}</td></tr>`).join('')}</table></div>` : ''}${(tl.utility_parts || []).length ? `<h4>Utility</h4><div class="tbl"><table><tr><th>Ability</th><th>Why</th><th class="num">Points</th></tr>${tl.utility_parts.map(c => `<tr><td>${esc(c.ability)}</td><td class="small">${esc(c.why)}</td><td class="num">${esc(c.value)}</td></tr>`).join('')}</table></div>` : ''}${tl.sustain != null ? `<h4>Survival</h4><p class="small">${(() => { const b = tl.tank_breakdown || {}; return b.tol_phys ? `With mid-game gear: ${fmt(b.hp_pool)} HP, takes ${fmt(Math.round(b.phys_damage_taken * 1000) / 10)}% of physical and ${fmt(Math.round(b.spell_damage_taken * 1000) / 10)}% of spell damage, heals ${fmt(b.recovery_pct_per_s)}% of max HP per second. Could stand in front of a boss dealing up to ${fmt(Math.round(b.tol_phys / 1e6))} million physical or ${fmt(Math.round(b.tol_spell / 1e6))} million spell damage per second for a minute. Holds ${b.bosses_held} of the map's ${b.bosses_total} mid to late bosses.` : ''; })()}${tl.afk_sustain != null ? ` Left alone against a mid-game pack it nets ${tl.afk_sustain >= 0 ? '+' : ''}${fmt(tl.afk_sustain)}% of max HP per second.` : ''}</p>` : ''}${(tl.tank_parts || []).length ? `<div class="tbl"><table><tr><th>Part</th><th>Ability</th><th>What counts</th></tr>${tl.tank_parts.map(c => `<tr><td class="small">${esc(c.part || '')}</td><td>${esc(c.ability)}</td><td class="small">${esc(c.why)}</td></tr>`).join('')}</table></div>` : ''}</details>` : ''}`;
  };
  const role = r => r.role || '';
  const safety = o => { if (o.afk_safe == null) { const r = o.afk_passive && o.afk_passive.recovery_pct_per_s; if (r == null) return ['', '']; return r > 0.1 ? ['Survives', 'ok'] : ['Dies if left alone', 'bad']; } return o.afk_safe ? ['Survives', 'ok'] : ['Dies if left alone', 'bad']; };
  const GRADE = v => v >= .8 ? 'S' : v >= .55 ? 'A' : v >= .35 ? 'B' : v >= .2 ? 'C' : 'D';
  const gtag = (g, raw) => `<span class="grade g${g}" title="${esc(raw)}">${g}</span>`;
  P.tierlist = (_, f) => {
    const T = W.tierlist; if (!T || !T.heroes) return '<h2>Tier list</h2><p class="small">Not built yet.</p>';
    const COLS = ['solo', 'boss', 'aoe', 'afk', 'utility', 'tank']; const key = COLS.includes(f.sort) ? f.sort : 'solo'; const f2p = f.f2p === '1'; const stage = ['early', 'mid', 'late'].includes(f.stage) ? f.stage : 'mid'; const early = f.early === '1';
    const KR = f.kain === '3' ? 3 : (f.kain === '1' || f.kain === '2') ? 2 : 0; const kain = KR > 0;   /* Kain 2% / evolved Kain 3% of max HP per attack */
    const AURA = KR === 3 ? 0.06 : 0.02;   /* Kain counts as summoned: its Vampiric Aura heals 2% (evolved 6%) of basic-attack damage, melee weapons only */
    const HIT = (((T.stages || {})[early ? 'early' : stage]) || {}).basic_hit || 0;
    const kainPct = (o, sw) => { const b = o.tank_breakdown || {}; return KR * sw + (o.melee && b.hp_pool ? 100 * AURA * HIT / b.hp_pool * sw : 0); };
    const base = r => early && r.t1 ? r.t1 : stage === 'early' && r.early ? r.early : stage === 'late' && r.late ? r.late : r;
    /* v14: the lifesteal box runs the same math as the tier list. Tank = how large a boss the hero could stand in front of
       for a minute (physical and spell tolerance on a log scale against the best hero). Kain adds 2% of max HP per attack
       to the healing. Survives if left alone = its no-click healing covers a mid-game pack. */
    const tolOf = (hp, p, s, ev, heal, fs) => { const e = Math.min(0.95, (ev || 0) > 1 ? ev / 100 : (ev || 0)); const bud = hp / (fs || 60) + hp * Math.max(0, heal) / 100; return [bud / Math.max(1e-6, p * (1 - e)), bud / Math.max(1e-6, s)]; };
    const tolScore = (t, best, R) => { const f = (x, b) => Math.max(0, Math.min(1, Math.log(Math.max(x, 1e-9) * R / b) / Math.log(R))); return 100 * (0.5 * f(t[0], best[0]) + 0.5 * f(t[1], best[1])); };
    /* v16 Tank: 60% the size of hit survived (HP / damage taken, evasion at half) + 40% healing capped at 10% of max HP/s, log scales
       below the best hero in view, x0.9, +10 for a taunt. The lifesteal pet adds to the healing (still capped). */
    const tankRaw = (hp, p, s, ev, heal, fs, cap) => { const e = Math.min(0.95, (ev || 0) > 1 ? ev / 100 : (ev || 0)); const h = Math.min(Math.max(0, heal), cap || 10) / 100 * hp + hp / (fs || 60); return [hp / Math.max(1e-6, p * (1 - 0.5 * e)), hp / Math.max(1e-6, s), h / Math.max(1e-6, p * (1 - e)), h / Math.max(1e-6, s)]; };
    const tankScore = (raw, best, b, taunt) => { const L = (x, bb, R) => Math.max(0, Math.min(1, Math.log(Math.max(x, 1e-9) * R / bb) / Math.log(R))); const w = b.tank_w || [0.6, 0.4]; const bs = (L(raw[0], best[0], b.burst_range || 100) + L(raw[1], best[1], b.burst_range || 100)) / 2, ss = (L(raw[2], best[2], b.sus_range || 1000) + L(raw[3], best[3], b.sus_range || 1000)) / 2; return 100 * (b.tank_scale || 0.9) * (w[0] * bs + w[1] * ss) + (taunt ? (b.taunt_bonus || 10) : 0); };
    const kainRaw = o => { const b = o.tank_breakdown || {}; return tankRaw(b.hp_pool, b.phys_damage_taken, b.spell_damage_taken, b.evasion, (b.recovery_pct_per_s || 0) + kainPct(o, o.swings || 0), b.fight_s, b.heal_cap); };
    const KBEST = (() => { const all = T.heroes.map(r => kainRaw(base(r))); return [0, 1, 2, 3].map(i => Math.max(...all.map(x => x[i]))); })();
    const dmgPart = o => Math.max(0, (o.afk || 0) / (o.afk_safe ? 1 : 0.5) - 0.5 * (o.afk_tank || 0));
    const withKain = o => { const b = o.tank_breakdown; if (!b || !kain || !b.tank_best) return o;
      const tank = Math.min(100, Math.round(tankScore(kainRaw(o), KBEST, b, b.taunt)));
      const ap = o.afk_passive || {}; const net = (o.afk_sustain || 0) + kainPct(o, o.swings_afk || 0); const safe = net >= 0;
      const at = Math.min(100, Math.round(tankScore(tankRaw(b.hp_pool, b.afk_phys_taken || b.phys_damage_taken, b.afk_spell_taken || b.spell_damage_taken, ap.evasion, (ap.recovery_pct_per_s || 0) + kainPct(o, o.swings_afk || 0), b.fight_s, b.heal_cap), KBEST, b, false)));
      return { ...o, tank, afk_tank: at, afk_safe: safe, afk_sustain: +net.toFixed(2), afk: +((dmgPart(o) + 0.5 * at) * (safe ? 1 : 0.5)).toFixed(1), afk_passive: { ...ap, recovery_pct_per_s: (ap.recovery_pct_per_s || 0) + kainPct(o, o.swings_afk || 0) } }; };
    const src = r => withKain(base(r));
    const pool = T.heroes.filter(r => !f2p || r.free !== false);
    const max = {}; for (const k of ['boss', 'aoe', 'afk', 'utility', 'tank']) max[k] = Math.max(1, ...pool.map(r => src(r)[k] || 0));
    const norm = (r, k) => (src(r)[k] || 0) / max[k];
    const TLO = Math.min(...pool.map(r => src(r).tank || 0)), THI = Math.max(1, ...pool.map(r => src(r).tank || 0));
    const solo = r => Math.pow(((src(r).tank || 0) - TLO + 5) / (THI - TLO + 5), 0.6) * Math.pow(0.8 * norm(r, 'boss') + 0.2 * norm(r, 'aoe'), 0.4);   /* v16: survival and damage both needed */
    const SAFE = { 'Survives': 1, 'Dies if left alone': 0.4 };
    const afkv = r => norm(r, 'afk');
    const afkMax = Math.max(0.001, ...pool.map(afkv));
    const val = (r, k) => k === 'solo' ? solo(r) : k === 'afk' ? afkv(r) / afkMax : norm(r, k);
    const rows = [...pool].sort((a, b) => val(b, key) - val(a, key)); const topSolo = Math.max(...pool.map(solo), 0.001);
    const LBL = { solo: 'Solo', boss: 'Boss damage', aoe: 'AoE damage', afk: 'AFK farm', utility: 'Utility (party)', tank: 'Tank (survival)' };
    const colv = k => pool.map(x => val(x, k)); const rankG = (k, v) => { if (!(v > 0)) return 'D'; const vs = colv(k); const above = vs.filter(x => x > v).length / vs.length; const mx = Math.max(...vs, 0.001); const g = above < 0.2 ? 'S' : above < 0.45 ? 'A' : above < 0.72 ? 'B' : above < 0.9 ? 'C' : 'D'; const cap = v < 0.15 * mx ? 'C' : v < 0.35 * mx ? 'B' : 'S'; return 'SABCD'.indexOf(g) > 'SABCD'.indexOf(cap) ? g : cap; };
    const cellG = (r, k) => k === 'solo' ? gtag(rankG('solo', solo(r)), 'solo score ' + Math.round(100 * solo(r) / topSolo)) : k === 'afk' ? gtag(rankG('afk', val(r, 'afk')), 'AFK farm ' + fmt(src(r).afk) + ' · no-click damage × stat per second: ' + fmt(src(r).afk_dps) + ' · no-click survival ' + fmt(src(r).afk_tank) + ' · ' + safety(src(r))[0]) : gtag(rankG(k, val(r, k)), (k === 'utility' || k === 'tank' ? '' : '× stat per second: ') + fmt(src(r)[k]));
    return `<h2>Hero tier list</h2><p class="small">${(() => { const S = (T.stages || {})[early ? 'early' : stage]; return S ? `${early ? 'Tier 1 (starting form)' : 'Tier 2'} of each hero in zones ${S.zones[0]} to ${S.zones[1]}: free gear up to there (+${fmt(S.gear_armor)} armor, +${S.gear_as}% attack speed), ${fmt(S.main / 1e6)} million main stat and ${fmt(S.secondary / 1e6)} million of each other stat bought. ` : ''; })()}No supporter items. Grades are by rank within each column (S = top fifth, A = next quarter, B = middle, C, D), hover a grade for the number.</p><div class="card warn"><p style="margin:0 0 8px;font-size:17px"><b>READ THIS FIRST. This list is one person's math and opinion. It is not the truth.</b></p><ul style="margin:0"><li>Grades come from ability numbers, not from playing. Anything within one grade is a coin flip.</li><li>It ignores <b>range</b> (ranged vs melee), <b>boss mechanics</b> (a revive, a taunt or magic immunity can beat any damage number on a given boss), <b>misses</b> (evasion, spell immunity) and <b>your attack speed</b> (each stage assumes its best free glove, at the attack-speed cap mana-loop heroes like Abyss are far stronger).</li><li>Every hero has a place in a party. An aura nobody else has can matter more than any grade here.</li><li><b>Role tags</b> say what a kit can do, not what the hero is: Healer = it heals the party at least 8% of max HP per second, no Damage tag does not mean it deals no damage.</li><li><b>Try heroes yourself.</b> Do not use this list to call for buffs or nerfs.</li></ul></div><details><summary>How the scores are built</summary><ul>${(T.assumptions || []).map(x => `<li>${esc(x)}</li>`).join('')}</ul></details>
    ${subtabs('tierlist', 'sort', Object.entries(LBL), key)}<div class="tl-ctrl"><span class="tl-grp"><b>Stage:</b>${[['early', 'Early'], ['mid', 'Mid'], ['late', 'Late']].map(([k, l]) => `<label><input type="radio" name="tlstage" value="${k}" ${stage === k ? 'checked' : ''}> ${l}</label>`).join('')}</span><span class="tl-grp"><b>Lifesteal pet:</b><select id="kainsel" class="tl-sel" aria-label="Lifesteal pet">${[['0', 'none'], ['2', 'Kain'], ['3', 'Evolved Kain']].map(([v, l]) => `<option value="${v}" ${String(KR) === v ? 'selected' : ''}>${l}</option>`).join('')}</select></span><span class="tl-grp"><label><input type="checkbox" id="early" ${early ? 'checked' : ''}> Tier 1</label><label><input type="checkbox" id="f2p" ${f2p ? 'checked' : ''}> Free to play only</label></span></div>
    <div class="tbl"><table class="sortable"><tr><th>#</th><th>Hero</th><th>Solo</th><th>Boss</th><th>AoE</th><th>AFK farm</th><th>Utility</th><th>Tank</th><th>If left alone</th><th>Note</th></tr>${rows.map((r, i) => { const s = safety(src(r)); return `<tr><td>${i + 1}</td><td style="white-space:nowrap">${img((PORT[r.name] || [])[1] || (PORT[r.name] || [])[0], 36)} ${link('hero', r.name, r.name)} ${r.free === false ? tag('supporter', 'acc') : ''}<br><span class="small">${esc(role(src(r)))}</span></td><td>${cellG(r, 'solo')}</td><td>${cellG(r, 'boss')}</td><td>${cellG(r, 'aoe')}</td><td>${cellG(r, 'afk')}</td><td>${cellG(r, 'utility')}</td><td>${cellG(r, 'tank')}</td><td>${s[0] ? `<span class="tag ${s[1]}" title="${src(r).afk_sustain != null ? 'left alone against a mid-game pack: ' + (src(r).afk_sustain >= 0 ? '+' : '') + fmt(src(r).afk_sustain) + '% of max HP per second' : ''}">${s[0]}</span>` : ''}</td><td class="small">${esc(r.notes || '')}${(src(r).unique_effects || []).length ? `<br>${src(r).unique_effects.map(u => `<span class="tag ok" style="text-transform:none;letter-spacing:0">only hero: ${esc(u)}</span>`).join(' ')}` : ''}</td></tr>`; }).join('')}</table></div>
`;
  };
  K.hooks.push((page, out) => { if (page !== 'tierlist') return; out.querySelectorAll('input[name=tlstage]').forEach(r => r.addEventListener('change', () => { K.filters.stage = r.value; K.route(); })); const ks = out.querySelector('#kainsel'); if (ks) ks.addEventListener('change', () => { K.filters.kain = ks.value; K.route(); }); for (const id of ['f2p', 'early']) { const cb = out.querySelector('#' + id); if (cb) cb.addEventListener('change', () => { K.filters[id] = cb.checked ? '1' : '0'; K.route(); }); } });
  KL.hero = 'Hero / ability';
  for (const h of HM) { if (h.skin || h.tier > 2) continue; INDEX.push({ k: 'hero', id: h.lineage, t: h.lineage + ' tier ' + h.tier, s: 'hero · ' + h.stat + (h.donation_flag ? ' · supporter' : ''), w: 3 }); for (const a of (h.abilities || [])) if (!/^(Move to|Inventory)/.test(a.name)) INDEX.push({ k: 'hero', id: h.lineage, t: a.name + ' (' + h.name + ')', s: 'ability · ' + String(a.tooltip || '').slice(0, 100), w: 1 }); }
})(window.WK);
