/* Items list + item page, Recipes tab - items from the map's object data, drops/recipes from the 1.1.0 script */
(function (K) {
  const { W, I, M, R, esc, link, tag, icon, iname, ilink, statLine, tipHtml, madeBy, usedIn, mlink, zlink, pct, fmt, rtable, gen, P, INDEX, KL, subtabs, filterBox, hooks } = K;
  const ITEMS = Object.values(I);
  const TYPES = [...new Set(ITEMS.map(i => i.type))].sort();
  const SRC = { drop: 'Monster drop', recipe: 'Recipe', shop: 'Shop', ticket: 'Ticket dungeon', supporter: 'Supporter reward', 'party dungeon': 'Party dungeon reward' };
  const dropCell = i => { const d = [...i.drops].sort((a, b) => b.c - a.c); return d.slice(0, 2).map(x => mlink(x.m) + ' <span class="small">' + pct(x.c) + '</span>').join('; ') + (d.length > 2 ? ' …' : ''); };
  const TYPE_ORDER = ['Weapon', 'Armor', 'Gloves', 'Accessory', 'Gem', 'Hidden', 'Pet gear', 'Material', 'Consumable', 'Ticket', 'Stat book', 'Companion'];
  const TYPES2 = TYPE_ORDER.filter(x => ITEMS.some(i => i.type === x));
  const FAM = {}; for (const i of ITEMS) (FAM[i.family] = FAM[i.family] || []).push(i);
  const famRep = list => list.slice().sort((a, b) => (a.level || 0) - (b.level || 0) || String(a.variant || '').localeCompare(String(b.variant || '')))[0];
  const famLink = i => `<a href="#item/${i.id}">${icon(i.id)}<span style="${i.color ? 'color:' + i.color : ''}">${esc(i.family)}</span></a>`;
  const famLabel = list => { const lv = list.map(x => x.level).filter(x => x != null); const v = [...new Set(list.map(x => x.variant).filter(Boolean))]; return (lv.length ? ` <span class="small">+${Math.min(...lv)} to +${Math.max(...lv)}</span>` : '') + (v.length ? ` <span class="small">[${esc(v.join('/'))}]</span>` : ''); };
  const REALMS = [...new Set(W.zones.map(z => z.realm))]; const ZZ = {}; for (const z of W.zones) ZZ[z.id] = z;
  const zoneOf = mid => { const m = M[mid]; if (!m || !m.zones.length) return null; return m.zones.map(z => z.zone).sort((a, b) => (ZZ[a] ? ZZ[a].order : 99) - (ZZ[b] ? ZZ[b].order : 99))[0]; };
  const BYZONE = {}; for (const i of ITEMS) { const zs = new Set(); for (const d of i.drops) { const z = zoneOf(d.m); if (z) zs.add(z); } for (const s of (i.shop || [])) if (s.zone) zs.add(s.zone); for (const z of zs) (BYZONE[z] = BYZONE[z] || []).push(i); }
  const itemsByZone = realm => W.zones.filter(z => z.realm === realm).map(z => { let list = BYZONE[z.id] || []; if (!list.length) return ''; const seen = new Set(); list = list.filter(i => { const k = i.type + '|' + i.family; if (seen.has(k)) return false; seen.add(k); return true; }); const types = TYPE_ORDER.filter(x => list.some(i => i.type === x)).concat([...new Set(list.map(i => i.type))].filter(x => !TYPE_ORDER.includes(x)));
    const how = i => { const d = i.drops.filter(x => zoneOf(x.m) === z.id).sort((a, b) => b.c - a.c)[0]; const s = (i.shop || []).find(x => x.zone === z.id); return [d ? mlink(d.m) + ' <span class="small">' + pct(d.c) + '</span>' : '', s ? '<span class="small">shop · ' + (s.gold ? fmt(s.gold) + ' gold' : '') + (s.lumber ? fmt(s.lumber) + ' lumber' : '') + '</span>' : ''].filter(Boolean).join(' · '); };
    return `<div class="card"><h3>${link('zone', z.id, z.name)} <span class="small">#${z.order}</span></h3><div class="tbl"><table><tr><th>Type</th><th>Item</th><th>From</th></tr>${types.map(tp => list.filter(i => i.type === tp).map((i, n, arr) => `<tr>${n === 0 ? `<td rowspan="${arr.length}" class="small">${esc(tp)}</td>` : ''}<td>${famLink(famRep(FAM[i.family].filter(x => x.type === i.type)))}${famLabel(FAM[i.family].filter(x => x.type === i.type))}</td><td class="small">${how(i)}</td></tr>`).join('')).join('')}</table></div></div>`; }).join('');
  P.items = (_, f) => {
    const view = f.view === 'type' ? 'type' : 'zone';
    const head = `<h2>Items</h2>${subtabs('items', 'view', [['zone', 'By zone'], ['type', 'By type']], view)}`;
    if (view === 'zone') { const realm = REALMS.includes(f.realm) ? f.realm : REALMS[0]; return head + `<p class="small">What drops or is sold in each zone. Crafted gear is under ${link('recipes', '', 'Recipes')}.</p>` + subtabs('items', 'realm', REALMS.map(r => [r, r]), realm) + itemsByZone(realm); }
    const t = TYPES2.includes(f.type) ? f.type : 'Weapon', q = (f.q || '').toLowerCase(), all = f.all === '1'; const src = ITEMS.some(i => i.type === t && i.src.includes(f.src)) ? (f.src || '') : '';
    let rows = ITEMS.filter(i => (!t || i.type === t) && (!q || i.name.toLowerCase().includes(q)) && (!src || (src === 'none' ? !i.src.length : i.src.includes(src))));
    if (!all) { const seen = new Set(); rows = rows.filter(i => { if (seen.has(i.family)) return false; seen.add(i.family); return true; }).map(i => famRep(FAM[i.family].filter(x => x.type === i.type))); }
    rows.sort((a, b) => (a.prog || 99) - (b.prog || 99) || (a.depth || 0) - (b.depth || 0) || a.family.localeCompare(b.family) || (a.level || 0) - (b.level || 0));
    return `${head}${subtabs('items', 'type', TYPES2.map(x => [x, x]), t)}${filterBox('filter by name', f.q)}<p class="small"><label><input type="checkbox" id="allitems" ${all ? 'checked' : ''}> show every level and stat variant</label></p>${(() => { const inType = ITEMS.filter(i => !t || i.type === t); const chips = [['drop', 'Monster drop'], ['recipe', 'Recipe'], ['shop', 'Shop'], ['ticket', 'Ticket'], ['party dungeon', 'Party dungeon'], ['supporter', 'Supporter reward']].filter(([k]) => inType.some(i => i.src.includes(k))); return chips.length > 1 ? subtabs('items', 'src', [['', 'Any source'], ...chips], chips.some(([k]) => k === src) ? src : '') : ''; })()}<p class="small">${rows.length} ${all ? 'items' : 'items, levels and stat variants folded'}, in progression order</p>
    <div class="tbl"><table class="sortable"><tr><th>Item</th><th>Stats${all ? '' : ' (first level)'}</th><th>Dropped by</th></tr>${rows.slice(0, 500).map(i => `<tr><td>${all ? ilink(i.id) : famLink(i)}${famLabel(FAM[i.family].filter(x => x.type === i.type))}</td><td class="small">${i.stats.map(statLine).join(', ')}</td><td class="small">${dropCell(i) || (i.shop && i.shop.length ? 'shop' : i.src.includes('recipe') ? 'crafted' : '')}</td></tr>`).join('')}</table></div>${rows.length > 500 ? '<p class="small">Showing the first 500. Narrow the filter.</p>' : ''}`;
  };
  hooks.push((page, out) => { if (page !== 'items') return; const cb = out.querySelector('#allitems'); if (cb) cb.addEventListener('change', () => { K.filters.all = cb.checked ? '1' : '0'; K.route(); }); });
  hooks.push((page, out) => { if (page !== 'recipes') return; const cb = out.querySelector('#enh'); if (cb) cb.addEventListener('change', () => { K.filters.enh = cb.checked ? '1' : '0'; K.route(); }); });
  P.item = id => {
    const i = I[id]; if (!i) return '<p>Unknown item.</p>'; const dr = [...i.drops].sort((a, b) => b.c - a.c); const mb = madeBy(id), u = usedIn(id);
    const fam = FAM[i.family].filter(x => x.id !== id).sort((a, b) => (a.level || 0) - (b.level || 0));
    return `<h2>${icon(id)} ${iname(i)} ${tag(i.type, 'acc')}</h2>
    ${(() => { const nx = u[0]; if (!nx) return ''; const mats = nx.in.filter(([k]) => k !== id); const m = mats.map(([k, n]) => { const it = I[k]; const best = it ? [...it.drops].sort((a, b) => b.c - a.c)[0] : null; return (n > 1 ? fmt(n) + '× ' : '') + ilink(k) + (best ? ` <span class="small">(${mlink(best.m)} ${pct(best.c)})</span>` : ''); }).join(' + '); return `<p><b>Next:</b> ${ilink(nx.out)}${m ? ', needs ' + m : ''}${nx.chance != null ? ` <span class="small">· ${pct(nx.chance_eff != null ? nx.chance_eff : nx.chance)} success</span>` : ''}</p>`; })()}
    <div class="tip">${tipHtml(i.tip) || '<span class="small">no tooltip</span>'}</div>
    ${i.companion ? `<p>Companion item: put it in a bag to turn the bag into ${mlink(i.companion)}. See ${link('pets', '', 'Pets')}.</p>` : ''}
    ${i.shop ? `<h3>Sold in</h3><ul>${i.shop.map(s => `<li>${zlink(s.zone)} · ${esc(s.shop)} · ${s.gold ? fmt(s.gold) + ' gold' : ''}${s.lumber ? fmt(s.lumber) + ' lumber' : ''}</li>`).join('')}</ul>` : ''}
    ${dr.length ? `<h3>Dropped by</h3><div class="tbl"><table><tr><th>Monster</th><th class="num">Base chance</th><th class="num">Rolls</th><th>Where</th></tr>${dr.map(x => { const m = M[x.m]; return `<tr><td>${mlink(x.m)}</td><td class="num">${pct(x.c)}</td><td class="num">${x.r}</td><td class="small">${m ? [...new Set(m.zones.map(z => z.zone))].map(zlink).join('; ') : ''}</td></tr>`; }).join('')}</table></div>` : ''}
    ${(() => { const famAll = FAM[i.family].filter(x => x.type === i.type && x.level != null); if (famAll.length < 3) return ''; const steps = R.filter(r => famAll.some(x => x.id === r.out) && r.in.some(([k]) => famAll.some(x => x.id === k))).sort((a, b) => (I[a.out].level || 0) - (I[b.out].level || 0)); if (!steps.length) return ''; return `<h3>Enhancement ladder</h3><div class="tbl"><table><tr><th>Step</th><th>Materials</th><th class="num">Success</th></tr>${steps.map(r => `<tr><td>${ilink(r.out)}</td><td class="small">${r.in.filter(([k]) => !famAll.some(x => x.id === k)).map(([k, n]) => (n > 1 ? fmt(n) + '× ' : '') + ilink(k)).join(' + ') || '-'}</td><td class="num">${pct(r.chance_eff != null ? r.chance_eff : r.chance)}</td></tr>`).join('')}</table></div>`; })()}
    ${mb.length ? `<h3>Made from</h3>${rtable(mb)}` : ''}${u.length ? `<h3>Used to make</h3>${rtable(u)}` : ''}
    ${(() => { if (!mb.length) return ''; const leaves = {}; const seen = new Set(); const walk = (k, depth) => { if (depth > 8 || seen.has(k)) return; seen.add(k); const it = I[k]; if (!it) return; const recs = R.filter(r => r.out === k); if (it.drops.length || !recs.length) { const best = [...it.drops].sort((a, b) => b.c - a.c)[0]; leaves[k] = best ? { m: best.m, c: best.c } : (it.shop ? { shop: it.shop[0] } : null); return; } for (const [x] of recs[0].in) walk(x, depth + 1); }; for (const [x] of mb[0].in) walk(x, 1); const ks = Object.keys(leaves).filter(k => k !== id); if (!ks.length) return ''; return `<h3>Where the materials come from</h3><ul>${ks.map(k => `<li>${ilink(k)} <span class="small">${leaves[k] && leaves[k].m ? '· ' + mlink(leaves[k].m) + ' ' + pct(leaves[k].c) : leaves[k] && leaves[k].shop ? '· sold at ' + esc(leaves[k].shop.shop) : '· supporter reward'}</span></li>`).join('')}</ul>`; })()}
    ${!dr.length && !mb.length && !i.shop && i.src.includes('supporter') ? `<p class="small">Supporter reward item.</p>` : ''}
    ${fam.length ? `<details><summary>${fam.length} other levels / variants of ${esc(i.family)}</summary><p>${fam.map(x => ilink(x.id)).join(' · ')}</p></details>` : ''}`;
  };
  /* recipes: grouped by result family */
  const G = W.recipe_groups || [];
  const RBYID = {}; for (const r of R) RBYID[r.id] = r;
  const gname = (fam, g) => { const rep = (FAM[fam] || []).find(x => !g || x.type === g.type) || (FAM[fam] || [])[0]; return rep ? `<a href="#item/${rep.id}">${icon(rep.id)}${esc(fam)}</a>` : esc(fam); };
  const grow = g => { const r = RBYID[g.first]; const lv = g.levels ? ` <span class="small">${g.levels[0] === g.levels[1] ? '+' + g.levels[0] : '+' + g.levels[0] + ' → +' + g.levels[1]}</span>` : ''; const v = g.variants.length ? ` <span class="small">[${g.variants.join('/')}]</span>` : '';
    const mats = (g.self ? [`${esc(g.family)}${g.levels ? ' (previous level)' : ''}`] : []).concat(g.mats.map(([m, n]) => (n > 1 ? fmt(n) + '× ' : '') + gname(m))).join(' + ');
    const ch = g.chance_min == null ? '' : g.chance_min === g.chance_max ? pct(g.chance_min) : `${pct(g.chance_max)} → ${pct(g.chance_min)}`;
    return `<tr><td>${gname(g.family, g)}${lv}${v}</td><td class="small">${mats}</td><td class="num">${ch}</td><td class="small">${esc(g.kind)}${g.n > 1 ? ` · ${g.n} steps` : ''}</td></tr>`; };
  P.recipes = (_, f) => {
    const types = [...TYPE_ORDER.filter(x => G.some(g => g.type === x)), 'Other'].filter(x => G.some(g => g.type === x)); const t = types.includes(f.type) ? f.type : types[0]; const q = (f.q || '').toLowerCase();
    const showEnh = f.enh === '1' || !G.some(g => g.type === t && !/^Enhancement/.test(g.kind));
    const rows = G.filter(g => g.type === t && (showEnh || !/^Enhancement/.test(g.kind)) && (!q || g.family.toLowerCase().includes(q) || g.mats.some(([m]) => String(m).toLowerCase().includes(q)))).sort((a, b) => (a.prog || 99) - (b.prog || 99) || (a.depth || 0) - (b.depth || 0) || a.family.localeCompare(b.family) || (a.levels ? a.levels[0] : 0) - (b.levels ? b.levels[0] : 0));
    return `<h2>Recipes</h2><p class="small">Type <code>-craft</code> with the items on your hero or carried backpacks. A failed enhancement loses the stone, not the item. A Perfect Enhancement Stone makes any enhancement step 100%.</p>
    ${subtabs('recipes', 'type', types.map(x => [x, x]), t)}${filterBox('filter by result or material', f.q)}<p class="small"><label><input type="checkbox" id="enh" ${showEnh ? 'checked' : ''}> show +N enhancement steps: previous level + Enhancement Stone</label> · ${rows.length} recipes in progression order</p><div class="tbl"><table class="sortable"><tr><th>Result</th><th>Materials</th><th class="num">Success</th><th>Kind</th></tr>${rows.map(grow).join('')}</table></div>`;
  };
  KL.item = 'Item';
  for (const fam of Object.keys(FAM)) { const list = FAM[fam]; const rep = famRep(list); const lv = list.map(x => x.level).filter(x => x != null); const v = [...new Set(list.map(x => x.variant).filter(Boolean))]; INDEX.push({ k: 'item', id: rep.id, t: fam + (lv.length && Math.max(...lv) > 1 ? ' +1…+' + Math.max(...lv) : '') + (v.length ? ' [' + v.join('/') + ']' : ''), s: rep.type + ' · ' + rep.stats.map(s => s[0] + ' +' + s[1]).join(' '), w: 2 }); }
})(window.WK);
