/* Game systems (verified tables) and the community guide */
(function (K) {
  const { W, I, M, Z, esc, link, tag, fmt, ilink, mlink, gen, P, INDEX, KL, subtabs, tbl } = K;
  const SY = W.systems || {};
  const NAMES = { attribute_enhancement: 'Attribute enhancement', relic_enhancement: 'Relic enhancement', ability_slots: 'Ability slots', potential: 'Potential', sailing: 'Sailing', party_dungeon: 'Party dungeon', awakening: 'Awakening', potions: 'Potions', stat_shop: 'Stat shop', hidden_items: 'Hidden items', dimension_link: 'Dimension Link' };
  if (W.supporter && W.supporter.link && !SY.dimension_link) SY.dimension_link = { summary: W.supporter.link.summary + ' ' + (W.supporter.link.points || ''), tables: [{ title: 'Perks by points', columns: ['Points', 'Perk'], rows: (W.supporter.link.perks || []).map(p => [p.points, p.perk]) }] };
  const SORDER = ['potions', 'stat_shop', 'awakening', 'ability_slots', 'attribute_enhancement', 'party_dungeon', 'potential', 'sailing', 'relic_enhancement', 'dimension_link'];
  const KEYS0 = Object.keys(SY).filter(k => !['unverified', 'rules'].includes(k) && SY[k] && typeof SY[k] === 'object' && !Array.isArray(SY[k]));
  const KEYS = [...KEYS0].sort((a, b) => (SORDER.indexOf(a) + 1 || 99) - (SORDER.indexOf(b) + 1 || 99));
  const cell = c => typeof c === 'object' && c && c.id ? (I[c.id] ? ilink(c.id) : M[c.id] ? mlink(c.id) : esc(c.name)) : esc(c);
  const table = t => `<h4>${esc(t.title || '')}</h4>${t.note ? `<p class="small">${esc(t.note)}</p>` : ''}<div class="tbl compact"><table><tr>${(t.columns || []).map(c => `<th>${esc(c)}</th>`).join('')}</tr>${(t.rows || []).map(r => `<tr>${r.map(c => `<td class="${typeof c === 'number' ? 'num' : ''}">${c == null ? '' : typeof c === 'number' ? fmt(c) : cell(c)}</td>`).join('')}</tr>`).join('')}</table></div>`;
  P.systems = (_, f) => {
    if (!KEYS.length) return '<h2>Game systems</h2><p class="small">Not built yet.</p>';
    const k = KEYS.includes(f.sys) ? f.sys : KEYS[0]; const s = SY[k];
    const head = `<h2>Game systems</h2>${subtabs('systems', 'sys', KEYS.map(x => [x, s && SY[x].title || NAMES[x] || x.replace(/_/g, ' ')]), k)}`;
    const shops = k === 'stat_shop' ? `<p>Stock and prices: ${W.zones.filter(z => (z.shops || []).length).map(z => link('zone', z.id, z.name)).join(' · ')}.</p>` : '';
    if (s.how) return `${head}<h3>${esc(s.title || NAMES[k] || k)}</h3><p>${esc(s.what || '')}${s.open ? ` <span class="small">· ${esc(s.open)}</span>` : ''}</p><div class="sys-grid"><div class="card"><h4 style="margin-top:0">How</h4><ol>${(s.how || []).map(x => `<li>${esc(x)}</li>`).join('')}</ol></div>${(s.tips || []).length ? `<div class="card"><h4 style="margin-top:0">Watch out</h4><ul>${s.tips.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div>` : ''}</div>${shops}${(s.items || []).length ? `<p class="small">Items: ${gen(s.items)}</p>` : ''}${(s.monsters || []).length ? `<p class="small">Bosses: ${gen(s.monsters)}</p>` : ''}${(s.tables || []).map(table).join('')}`;
    return `${head}<h3>${esc(NAMES[k] || k)}</h3><p>${esc(s.summary || '')}</p>${(s.rules || []).length ? `<ul>${s.rules.map(x => `<li>${esc(x)}</li>`).join('')}</ul>` : ''}${shops}${(s.items || []).length ? `<p>Items: ${gen(s.items)}</p>` : ''}${(s.tables || []).map(table).join('')}`;
  };
  /* ---- guides (verified progression + Stoner's route) ---- */
  P.guides = id => {
    const G = W.guides || [];
    let stat = 'STR'; try { stat = localStorage.getItem('cwgStat') || 'STR'; } catch (e) { }
    const VARS = {}; for (const it of Object.values(I)) if (it.variant) (VARS[it.family + '|' + it.type + '|' + (it.level || 0)] = VARS[it.family + '|' + it.type + '|' + (it.level || 0)] || {})[it.variant] = it.id;
    const swap = c => { const it = I[c]; if (!it || !it.variant || it.variant === stat) return c; const v = VARS[it.family + '|' + it.type + '|' + (it.level || 0)]; return v && v[stat] ? v[stat] : c; };
    const rich = s => esc(s).replace(/\{\{i:([A-Z0-9]{4})\}\}/g, (m, c) => ilink(swap(c))).replace(/\{\{m:([A-Za-z0-9]{4})\}\}/g, (m, c) => mlink(c)).replace(/\{\{z:(z\d\d)\}\}/g, (m, c) => Z[c] ? link('zone', c, Z[c].name) : c).replace(/\{\{l:([^|}]+)\|([^}]+)\}\}/g, (m, h, txt) => `<a href="#${h.replace(/&amp;/g, '&')}">${txt}</a>`);
    const f = K.filters; const g = G.find(x => x.id === id) || G[0]; if (!g) return '<h2>Guides</h2>';
    let done = {}; try { done = JSON.parse(localStorage.getItem('cwgGuideDone') || '{}') || {}; } catch (e) { done = {}; }
    let owned = {}; try { owned = JSON.parse(localStorage.getItem('cwgOwned') || '{}') || {}; } catch (e) { }
    const results = txt => { const i = txt.lastIndexOf('->'); return i < 0 ? [] : [...txt.slice(i).matchAll(/\{\{i:([A-Z0-9]{4})\}\}/g)].map(m => swap(m[1])); };
    const stepsHtml = (steps, key) => g.plain ? `<table class="steps plain">${(steps || []).map(st => `<tr>${st.h ? `<td class="small"><b>${esc(st.h)}</b></td>` : ''}<td${st.h ? '' : ' colspan="2"'}>${rich(st.t)}</td></tr>`).join('')}</table>` : (() => { let zone = null, n = 0; const numbered = g.id === 'gear'; const ownedDone = (steps || []).map(st => { const res = results(st.t); return g.id !== 'early-game' && res.length && res.every(x => owned[x]); }); let lastOwned = -1; ownedDone.forEach((v, i) => { if (v) lastOwned = i; }); return `<table class="steps${numbered ? ' route' : ''}">${(steps || []).map((st, i) => { const k = key + ':' + i; const res = results(st.t); const isDone = done[k] || i <= lastOwned; let head = ''; if (numbered && st.h !== zone && !/^Step /.test(st.h)) { zone = st.h; head = `<tr class="zh"><td colspan="4">${esc(zone)}</td></tr>`; } n++; const parts = numbered && st.t.includes('->') ? [st.t.slice(0, st.t.lastIndexOf('->')).trim(), st.t.slice(st.t.lastIndexOf('->') + 2).trim()] : null; return head + `<tr class="${isDone ? 'done' : ''}"><td><input type="checkbox" class="gstep" data-k="${k}" data-res="${res.join(',')}" ${isDone ? 'checked' : ''}></td>${numbered ? `<td class="small num">${n}</td><td>${parts ? rich(parts[0]) : rich(st.t)}</td><td>${parts ? '→ ' + rich(parts[1]) : ''}</td>` : `<td class="small"><b>${esc(st.h)}</b></td><td>${rich(st.t)}</td>`}</tr>`; }).join('')}</table>`; })();
    const secs = g.sections || [{ h: 'Steps', steps: g.steps }]; const cur = secs.some(s => s.h === f.gsec) && g.id === f.gid ? f.gsec : secs[0].h; f.gid = g.id;
    const si = secs.findIndex(s => s.h === cur);
    return `<h2>Guides</h2><div class="sub-tabs">${G.map(x => `<a href="#guides/${x.id}" class="${x.id === g.id ? 'on' : ''}">${esc(x.title)}</a>`).join('')}</div>${g.intro ? `<p class="small">${rich(g.intro)}</p>` : ''}${g.plain ? '' : `<p><b>Main stat:</b> ${['STR', 'AGI', 'INT'].map(s => `<label style="margin-right:10px"><input type="radio" name="stat" value="${s}" ${s === stat ? 'checked' : ''}> ${s}</label>`).join('')} <span class="small">items switch to your stat's version</span> &nbsp; <span class="small">☑ tick a step when done - everything above it is ticked too, unticking clears everything below. Early-game ticks also mark the same items in the gear guide (this browser)</span></p>`}${secs.length > 1 ? subtabs('guides/' + g.id, 'gsec', secs.map(s => [s.h, s.h]), cur) : ''}<div class="card"><h3>${esc(g.title)}${secs.length > 1 ? ' · ' + esc(cur) : ''}</h3>${secs[si].table ? `<div class="tbl"><table><tr>${secs[si].table.columns.map(c => `<th>${esc(c)}</th>`).join('')}</tr>${secs[si].table.rows.map(r => `<tr>${r.map((c, ci) => `<td class="${ci === 0 ? 'num' : ci === 1 ? '' : 'small'}">${ci === 1 ? `<b>${esc(c)}</b>` : esc(c)}</td>`).join('')}</tr>`).join('')}</table></div>` : stepsHtml(secs[si].steps, g.id + ':' + si)}</div>`;
  };
  const CHANGES = [
    ['22 Sep 2026', 'Where to farm next: pick your gear once and follow the next step for every slot. Two views, Simple and Detailed. "I have it" moves the slot on and ticks the gear checklist for you.'],
    ['22 Sep 2026', 'Gear progression checklists now run from the first piece to the last enhancement of every slot, with every material and its source in place.'],
    ['22 Sep 2026', 'Party dungeons: the Contribution and Permanent Engraving system, with every track and the cost of each level.'],
  ];
  P.changelog = () => `<h2>Changelog</h2><p class="small">What changed on the wiki, newest first.</p><div class="tbl"><table>${CHANGES.map(([d, x]) => `<tr><td class="small" style="white-space:nowrap">${esc(d)}</td><td>${esc(x)}</td></tr>`).join('')}</table></div>`;
  P.credits = () => `<h2>Credits</h2><ul><li>CWG RPG - Covenant of Warring Gods 1.1.0 by TheMidLane / Gwelawyr's RPG Ports. Discord: <a href="https://discord.gg/Z5Pf8exufw" target="_blank" rel="noopener">discord.gg/Z5Pf8exufw</a>.</li><li>Every number here comes from the map's own data.</li><li>Early-game route based on Stoner's guide. Hero portraits from the community wiki, item icons from the community 3.81 planner.</li><li>Built with Claude (Anthropic). The tier list is a calculation, not an in-game measurement.</li></ul>`;
  K.hooks.push((page, out) => { if (page !== 'guides') return; out.querySelectorAll('input[name=stat]').forEach(r => r.addEventListener('change', () => { try { localStorage.setItem('cwgStat', r.value); } catch (e) { } K.route(); })); out.querySelectorAll('input.gstep').forEach(cb => cb.addEventListener('change', () => { let d = {}; try { d = JSON.parse(localStorage.getItem('cwgGuideDone') || '{}') || {}; } catch (e) { } let o = {}; try { o = JSON.parse(localStorage.getItem('cwgOwned') || '{}') || {}; } catch (e) { } const all = [...out.querySelectorAll('input.gstep')]; const targets = cb.checked ? all.slice(0, all.indexOf(cb) + 1) : all.slice(all.indexOf(cb)); for (const c of targets) { c.checked = cb.checked; if (cb.checked) d[c.dataset.k] = 1; else delete d[c.dataset.k]; { const early = out.querySelector('.sub-tabs a.on') && /early-game/.test(out.querySelector('.sub-tabs a.on').getAttribute('href') || ''); for (const id of (c.dataset.res || '').split(',').filter(Boolean)) { if (!early && !K.GEAR_TYPES.has((K.I[id] || {}).type)) continue; if (cb.checked) o[id] = 1; else delete o[id]; } } c.closest('tr').classList.toggle('done', cb.checked); } try { localStorage.setItem('cwgGuideDone', JSON.stringify(d)); localStorage.setItem('cwgOwned', JSON.stringify(o)); } catch (e) { } })); });
  KL.guides = 'Guide'; for (const k of KEYS) KL['systems?sys=' + k] = 'Game system';
  for (const g of (W.guides || [])) INDEX.push({ k: 'guides', id: g.id, t: g.title, s: 'guide · ' + (g.intro || '').slice(0, 80), w: 4 });
  for (const k of KEYS) INDEX.push({ k: 'systems?sys=' + k, id: '', t: NAMES[k] || k, s: String((SY[k] || {}).what || (SY[k] || {}).summary || '').slice(0, 100), w: 3 });
})(window.WK);
